version: '3'

services:
  redis:
    image: redis:alpine
    environment:
      - DOMAIN_NAME=redis.${BASEHOST:-pimcore.dev}
    network_mode: bridge

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - DOMAIN_NAME=mysql.${BASEHOST:-pimcore.dev}
    command: --innodb-doublewrite=0
    network_mode: bridge

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - DOMAIN_NAME=mailcatcher.${BASEHOST:-pimcore.dev}
    network_mode: bridge

  application:
    image: dockerwest/php-pimcore:${PHPVERSION:-7.1}
    environment:
      - C_UID=${C_UID:-1000}
      - C_GID=${G_UID:-1000}
      - DEVELOPMENT=${DEVELOPMENT:-noprofile}
    volumes:
      - ${APPLICATION:-../pimcore}:/phpapp
    links:
      - mysql
      - redis
      - mailcatcher
    network_mode: bridge

  nginx:
    image: dockerwest/nginx-symfony:${NGINXVERSION:-stable}
    environment:
      - VIRTUAL_HOST=${BASEHOST:-pimcore.dev},www.${BASEHOST:-pimcore.dev},${EXTRAHOSTS}
      - VIRTUAL_PORT=80
    volumes:
      - ${APPLICATION:-../pimcore}:/phpapp
    links:
      - application
    network_mode: bridge

